eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'