server:
  port: 0

spring:
  application:
    name: cadastral

  jpa:
    generate-ddl: false
    
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cadastral
      auto-index-creation: true


  rabbitmq:
    host: localhost
    port: 5672
    username: un_user
    password: un_user

crud:
  rabbitmq:
    exchanges:
      exchangeAccommodations: crud.fanout.register-accommodations
      exchangeUsers: crud.fanout.register-users
    queues:
      accommodationQueue: crud.register-accommodations.queue
      userQueue: crud.register-users.queue

ead:
  serviceRegistry:
    username: un_user
    password: 'un_user'

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

app:
  uploads-dir: C:\Users\JabutiAzul\OneDrive\Documentos\GitHub\backend\cadastral\uploads\imoveis
