server:
  port: 8585

spring:
  application:
    name: cadastral

  jpa:
    generate-ddl: false
    
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cadastral
      auto-index-creation: true


  rabbitmq:
    host: localhost
    port: 5672
    username: un_user
    password: un_user

crud:
  rabbitmq:
    exchanges:
      exchangeAccommodations: crud.fanout.register-accommodations
      exchangeUsers: crud.fanout.register-users
    queues:
      accommodationQueue: crud.register-accommodations.queue
      userQueue: crud.register-users.queue

ead:
  serviceRegistry:
    username: un_user
    password: 'un_user'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  uploads-dir: C:/Users/Samuel Modesto/OneDrive/Documentos/Projetos/TCC/imovato/backend/cadastral/uploads/imoveis
