server:
  port: 0

spring:
  application:
    name: transacional
  datasource:
    url: jdbc:mysql://localhost:33060/transacional?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: un_user
    password: un_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host:  localhost
    port: 5672
    username: un_user
    password: un_user

  sleuth:
    sampler:
      probability: 1.0

  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC

crud:
  rabbitmq:
    exchanges:
      exchangeAccommodations: crud.fanout.register-accommodations
      exchangeUsers: crud.fanout.register-users
    queues:
      accommodationQueue: crud.register-accommodations.queue
      userQueue: crud.register-users.queue

ead:
  serviceRegistry:
    username: un_user
    password: 'un_user'
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

info:
  app: Microsserviço de Aluguel
  website: bla
  github: https://github.com/imovato

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}